// 予約登録
POST https://vrlssjrj4i.execute-api.us-east-1.amazonaws.com/dev/reservations HTTP/1.1
content-type: application/json

{
    "executeTimestamp": "2024-10-21T14:00:00Z",
}

###

// 予約一覧照会
GET https://vrlssjrj4i.execute-api.us-east-1.amazonaws.com/dev/reservations HTTP/1.1
content-type: application/json

###

// 予約個別照会
GET https://vrlssjrj4i.execute-api.us-east-1.amazonaws.com/dev/reservations/79f98d43-0135-4f7f-922d-171c25065e89 HTTP/1.1
content-type: application/json

###

// 予約個別更新
PUT https://vrlssjrj4i.execute-api.us-east-1.amazonaws.com/dev/reservations/79f98d43-0135-4f7f-922d-171c25065e89 HTTP/1.1
content-type: application/json

{
    "executeTimestamp": "2024-10-21T15:00:00Z",
}

###

// 予約削除
DELETE https://vrlssjrj4i.execute-api.us-east-1.amazonaws.com/dev/reservations/79f98d43-0135-4f7f-922d-171c25065e89 HTTP/1.1
content-type: application/json